---
name: 'OpenSRP web new Feature request.'
description: 'Use this to request for a new feature that is not available in the current application.'
title: '[New Feature Request] '
labels: 'New Feature Request'
assignees: '[]'
---
body:
  - type: markdown
      attributes:
        value: |
          Thanks for taking the time to fill out this new feature request!
  - type: textarea
      id: use_case
      attributes:
        label: Feature Use Case
        description: "Give a detailed use case of how this feature is to be used?"
        placeholder: "Needed to display what teams practitioners are assigned to"
      validations:
        required: true
  - type: textarea
      id: acceptance_criteria
      attributes:
        label: Acceptance criteria
        description: "What is the acceptance criteria for this feature?"
        placeholder: "Team assignments should be shown on the user details page."
      validations:
        required: true
  - type: textarea
      id: extra_info
      attributes:
        label: Relevant Information
        description: "Please share any other relevant information about the feature request or project."
        placeholder: " "
      validations:
        required: false

---
